package com.neofect.gts.services.sm.domain;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;

import lombok.Data;

@Alias("common")
@Data
public class SmCommon implements Serializable {

	private static final long serialVersionUID = -6612352392486944024L;

	private String code;
	private String label;
	private String vendorname;
	private String sitecode;
	private String sitename;
	private String sysname;
	private String plandiv;
	private String mcnt;
	private String mc01;
	private String mc02;
	private String mc03;
	private String mc04;
	private String mc05;
	private String mc06;
	private String mc07;
	private String mc08;
	private String mc09;
	private String mc10;
	private String mc11;
	private String mc12;
	private String realdiv;
	private String pcnt;
	private String p01;
	private String p02;
	private String p03;
	private String p04;
	private String p05;
	private String p06;
	private String p07;
	private String p08;
	private String p09;
	private String p10;
	private String p11;
	private String useyesno;
	private String dc01;
	private String dc02;
	private String dc03;
	private String dc04;
	private String dc05;
	private String dc06;
	private String dc07;
	private String dc08;
	private String dc09;
	private String dc10;
	private String dc11;
	private String dc12;
	private String dc13;
	private String dc14;
	private String dc15;
	private String dc16;
	private String dc17;
	private String dc18;
	private String dc19;
	private String dc20;
	private String dc21;
	private String dc22;
	private String dc23;
	private String dc24;
	private String dc25;
	private String dc26;
	private String dc27;
	private String dc28;
	private String dc29;
	private String dc30;
	private String dc31;
	private String p12;
	private String p13;
	private String p14;
	private String p15;
	private String p16;
	private String p17;
	private String p18;
	private String p19;
	private String p20;
	private String p21;
	private String p22;
	private String p23;
	private String p24;
	private String p25;
	private String p26;
	private String p27;
	private String p28;
	private String p29;
	private String p30;
	private String p31;
	private String prtseq;
	private String cnt;
	private String companycode;
	private String sysid;
	private String closecode;
	private String closename;
	private String fromdiv;
	private String fromdd;
	private String todiv;
	private String todd;
	private String remark;
}
