package com.neofect.gts.services.common.domain;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;

import lombok.Data;

@Alias("findAddCustCode")
@Data
public class FindAddCustCode implements Serializable{
	
	private static final long serialVersionUID = 4052346663226749150L;

	private String useYn;
	private String custTag;
	private String custCode;
	private String custName;
	private String owner;
	private String condition;
	private String category;
	private String zip;
	private String addr;
	private String addr2;
	private String tel;
	private String tel2;
	private String fax;
	private String tradeType;
	private String businessType;
	private String payGroup;
	private String bankCode;
	private String bankName;
	private String depositNo;
	private String depositOwner;
	private String buyCardNo;
	private String joinNo;
	private String companyNo;
	private String chargeName;
	private String registerNo;
	private String closingDate;
	private String inputDate;
	private String taxempDeptName;
	private String taxempName;
	private String taxempTel;
	private String taxempEmail;
	private String hqZip;
	private String hqAddr;
	private String hqAddr2;
	private String vendCode;
	private String vendType;
	private String validStdate;
	private String validEndate;
	private String billDepositNo;
	private String custGroup;
	private String remark;
	private String statusCode;
	private String openDate;
	private String custTag1;
	private String custTag2;
	private String custTag3;
	private String custTag4;
	private String custTag5;
	private String taxOfficeCode;
	private String attachDate;
	private String debtAmt;
	private String attachAmt;
	private String competentCourt;
	private String attachEndDate;
	private String attachReason;
	private String taxempComId;
	private String empNo;
	private String businessChkDate;
	private String useDept;
	private String email;
	private String depositFromdate;
	private String depositTodate;
	private String bankCode1;
	private String bankName1;
	private String depositNo1;
	private String depositOwner1;
	private String depositFromdate1;
	private String depositTodate1;
	private String bankCode2;
	private String bankName2;
	private String depositNo2;
	private String depositOwner2;
	private String depositFromdate2;
	private String depositTodate2;
	private String ebillBankCode;
	private String ebillBankName;
	private String ebillRegNo;
	private String ebillBankCode1;
	private String ebillBankName1;
	private String ebillRegNo1;
	private String ebillBankCode2;
	private String ebillBankName2;
	private String ebillRegNo2;
	private String ebillBankCode3;
	private String ebillBankName3;
	private String ebillRegNo3;
	private String arBankCode;
	private String arBankName;
	private String arDepositNo;
	private String arLoanAcntName;
	private String arLoanFromdate;
	private String arLoanTodate;
	private String arLoanLimit;
	private String arRecourseYn;
	private String arBankCode1;
	private String arBankName1;
	private String arDepositNo1;
	private String arLoanAcntName1;
	private String arLoanFromdate1;
	private String arLoanTodate1;
	private String arLoanLimit1;
	private String arRecourseYn1;
	private String arBankCode2;
	private String arBankName2;
	private String arDepositNo2;
	private String arLoanAcntName2;
	private String arLoanFromdate2;
	private String arLoanTodate2;
	private String arLoanLimit2;
	private String arRecourseYn2;
	private String arBankCode3;
	private String arBankName3;
	private String arDepositNo3;
	private String arLoanAcntName3;
	private String arLoanFromdate3;
	private String arLoanTodate3;
	private String arLoanLimit3;
	private String arRecourseYn3;
	private String holdingDate;
	private String holdingReason;
	private String holdingType;
	private String wcmsBusinessType;
	private String bankUse1;
	private String bankUse2;
	private String ebillBankUse1;
	private String ebillBankUse2;
	private String ebillBankUse3;
	private String arBankUse1;
	private String arBankUse2;
	private String arBankUse3;
	private String depositNoChk1;
	private String depositNoChk2;
	private String useDeptC;
	private String useDeptP;
	private String useDeptF;
	private String useDeptE;
	private String rcnt;
	private String code;
	private String label;
	private String buyrCorpNm;
	
}
